;;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(in-package #:euler)

(defun problem2 (odd even limit result)
  (if (< even limit)
      (problem2 (+ odd (* 2 even)) 
                (+ (* 2 odd) (* 3 even))
                limit 
                (+ result even))
      result))
